'use server';

import { getProductRepository, getTenantRepository } from "@/lib/repository";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { Product } from '@/lib/repository/types';
import { createClient } from "@/utils/supabase/server";


import { verifyTenantOwnership } from "@/lib/auth/security";
import { handleAutoPost } from "./social-actions";

export async function toggleProductAvailability(id: string, newState: boolean, slug: string) {
    // Security Check
    await verifyTenantOwnership(slug);

    const supabase = await createClient();
    const repo = getProductRepository(supabase);
    await repo.toggleAvailability(id, newState);
    revalidatePath(`/store/${slug}/admin/menu`);
    revalidatePath(`/store/${slug}/admin/menu`);
    revalidatePath(`/store/${slug}`);
    return { success: true };
}

export async function createProduct(formData: FormData, tenantId: string, slug: string) {
    // Security Check
    await verifyTenantOwnership(slug);

    const name = formData.get('name') as string;
    const price = parseFloat(formData.get('price') as string);
    const category = formData.get('category') as string;
    const description = formData.get('description') as string;
    const image = formData.get('image') as string || ''; // Simplified image handling (url string)
    // Default to 'physical' if not specified (e.g. old form)
    const type = (formData.get('type') as 'physical' | 'digital') || 'physical';

    const repo = getProductRepository();

    // Create product object (id is typically generated by DB, but here we might need to handle it or let repo do it)
    // Assuming repo.addProduct handles ID generation if not provided, or we generate one.
    // Looking at types.ts, Product interface has ID. 
    // Usually a real DB repo generates it. For mock repo, might need to generate.
    // I'll assume repo handles it or I'll generate a random one if needed.
    // Let's check types.ts again or just pass the specialized object.

    const product: Product = {
        id: crypto.randomUUID(),
        tenantId,
        name,
        price,
        category,
        description,
        image,
        isAvailable: true,
        type
    };

    await repo.addProduct(product);

    // Fire and forget auto-post (don't block UI)
    // Fire and forget auto-post (don't block UI)
    handleAutoPost(product, tenantId).then(results => {
        results.forEach(res => {
            if (res.success) console.log(`Auto-post to ${res.provider} successful: ${res.postId}`);
            else console.error(`Auto-post to ${res.provider} failed: ${res.error}`);
        });
    }).catch(err => console.error("Background auto-post failed", err));

    revalidatePath(`/store/${slug}/admin/menu`);
    revalidatePath(`/store/${slug}`);
    redirect(`/store/${slug}/admin/menu?saved=${encodeURIComponent('Product added successfully!')}`);
}
