/**
 * Customer-facing translations for the storefront, cart, order page,
 * and the WhatsApp order message format generated by the API.
 *
 * The merchant chooses a default in their store Settings (tenant.language).
 * Customers can override on the storefront via a flag picker; their choice
 * is persisted in localStorage.
 *
 * Conventions:
 *   - Every locale must have every key. TypeScript enforces this via
 *     Dictionary = typeof dictionaries.en.
 *   - Keep keys English even for non-English locales.
 *   - For RTL locales (Arabic), wrap text without unicode bidi markers —
 *     CSS `dir="rtl"` handles direction.
 */

export type Locale = 'en' | 'es' | 'fr' | 'ar' | 'pt' | 'id';

// RTL languages
export const RTL_LOCALES: Locale[] = ['ar'];
export const isRTL = (locale: Locale) => RTL_LOCALES.includes(locale);

export const SUPPORTED_LOCALES: { code: Locale; label: string; flag: string }[] = [
    { code: 'en', label: 'English',    flag: '🇺🇸' },
    { code: 'es', label: 'Español',    flag: '🇪🇸' },
    { code: 'pt', label: 'Português',  flag: '🇧🇷' },
    { code: 'fr', label: 'Français',   flag: '🇫🇷' },
    { code: 'ar', label: 'العربية',     flag: '🇸🇦' },
    { code: 'id', label: 'Indonesia',  flag: '🇮🇩' },
];

export const dictionaries = {
    en: {
        // ── Storefront ──────────────────────────────────────────────
        searchPlaceholder: "Search menu...",
        all: "All",
        addToOrder: "Add to Order",
        viewCart: "View Order",
        viewCartBtn: "View Cart",
        outOfStock: "Sold Out",
        items: "items",
        openNow: "Open Now",
        closed: "Closed",

        // ── Cart / Checkout ─────────────────────────────────────────
        emptyCart: "Your cart is empty",
        checkoutTitle: "Checkout",
        digital: "Digital",
        subtotal: "Subtotal",
        delivery: "Delivery",
        discount: "Discount",
        total: "Total",
        promoCode: "Promo Code",
        apply: "Apply",
        name: "Name",
        phone: "WhatsApp Number",
        email: "Email",
        address: "Delivery Address",
        pinCode: "Maps Link (Optional)",
        notes: "Notes",
        notesPlaceholder: "e.g. No onions, extra sauce, ring the doorbell...",
        addressPlaceholder: "Street, City, Building...",
        fullNamePlaceholder: "Full name",
        phonePlaceholder: "+1234567890",
        emailPlaceholder: "you@example.com",
        locationHelpPlaceholder: "e.g. Mall entrance, parking lot B...",
        paymentMethod: "Payment Method",
        paymentSlip: "Payment Slip",
        attachPaymentSlip: "Tap to attach payment screenshot",
        payNow: "Send Order",
        checkout: "Checkout via WhatsApp",

        // ── Toasts ──────────────────────────────────────────────────
        orderPlaced: "Order placed!",
        orderPlacedSuccess: "Order placed successfully!",
        redirectingToPayment: "Redirecting to payment...",
        redirectingToPaypal: "Redirecting to PayPal...",
        openingWhatsapp: "Opening WhatsApp...",
        geoNotSupported: "Geolocation is not supported by your browser",
        geoFailed: "Unable to retrieve your location",

        // ── Order receipt page ──────────────────────────────────────
        orderLabel: "Order",
        poweredBy: "Powered by",

        // ── WhatsApp order message ─────────────────────────────────
        newOrder: "NEW ORDER",
        customerDetails: "Customer Details",
        orderItems: "Order Items",
        paymentLabel: "Payment",
        notesLabel: "Notes",
        paymentSlipLabel: "Payment Slip",
        trackLabel: "Track",

        // ── Fulfillment methods ────────────────────────────────────
        fulfillmentDelivery: "Delivery",
        fulfillmentPickup: "Pickup",
        fulfillmentDinein: "Dine-in",
        fulfillmentPost: "Delivery by Post",
    },
    es: {
        searchPlaceholder: "Buscar en el menú...",
        all: "Todos",
        addToOrder: "Agregar",
        viewCart: "Ver Pedido",
        viewCartBtn: "Ver Carrito",
        outOfStock: "Agotado",
        items: "artículos",
        openNow: "Abierto",
        closed: "Cerrado",

        emptyCart: "Tu carrito está vacío",
        checkoutTitle: "Finalizar Pedido",
        digital: "Digital",
        subtotal: "Subtotal",
        delivery: "Envío",
        discount: "Descuento",
        total: "Total",
        promoCode: "Código Promocional",
        apply: "Aplicar",
        name: "Nombre",
        phone: "Número de WhatsApp",
        email: "Correo electrónico",
        address: "Dirección de Entrega",
        pinCode: "Link de Google Maps (Opcional)",
        notes: "Notas",
        notesPlaceholder: "ej. Sin cebolla, salsa extra, tocar el timbre...",
        addressPlaceholder: "Calle, Ciudad, Edificio...",
        fullNamePlaceholder: "Nombre completo",
        phonePlaceholder: "+1234567890",
        emailPlaceholder: "tu@ejemplo.com",
        locationHelpPlaceholder: "ej. Entrada del centro comercial, estacionamiento B...",
        paymentMethod: "Método de pago",
        paymentSlip: "Comprobante de pago",
        attachPaymentSlip: "Toca para adjuntar comprobante de pago",
        payNow: "Enviar Pedido",
        checkout: "Completar en WhatsApp",

        orderPlaced: "¡Pedido realizado!",
        orderPlacedSuccess: "¡Pedido realizado con éxito!",
        redirectingToPayment: "Redirigiendo al pago...",
        redirectingToPaypal: "Redirigiendo a PayPal...",
        openingWhatsapp: "Abriendo WhatsApp...",
        geoNotSupported: "Tu navegador no soporta geolocalización",
        geoFailed: "No se pudo obtener tu ubicación",

        orderLabel: "Pedido",
        poweredBy: "Creado con",

        newOrder: "NUEVO PEDIDO",
        customerDetails: "Datos del Cliente",
        orderItems: "Artículos del Pedido",
        paymentLabel: "Pago",
        notesLabel: "Notas",
        paymentSlipLabel: "Comprobante",
        trackLabel: "Seguimiento",

        fulfillmentDelivery: "Entrega",
        fulfillmentPickup: "Recoger",
        fulfillmentDinein: "Comer en el local",
        fulfillmentPost: "Envío por Correo",
    },
    fr: {
        searchPlaceholder: "Rechercher...",
        all: "Tous",
        addToOrder: "Ajouter",
        viewCart: "Voir Panier",
        viewCartBtn: "Voir le Panier",
        outOfStock: "Épuisé",
        items: "articles",
        openNow: "Ouvert",
        closed: "Fermé",

        emptyCart: "Votre panier est vide",
        checkoutTitle: "Commander",
        digital: "Numérique",
        subtotal: "Sous-total",
        delivery: "Livraison",
        discount: "Remise",
        total: "Total",
        promoCode: "Code Promo",
        apply: "Appliquer",
        name: "Nom",
        phone: "Numéro WhatsApp",
        email: "Email",
        address: "Adresse de livraison",
        pinCode: "Lien Maps (Optionnel)",
        notes: "Notes",
        notesPlaceholder: "ex. Sans oignons, sauce supplémentaire, sonner à la porte...",
        addressPlaceholder: "Rue, Ville, Bâtiment...",
        fullNamePlaceholder: "Nom complet",
        phonePlaceholder: "+1234567890",
        emailPlaceholder: "vous@exemple.com",
        locationHelpPlaceholder: "ex. Entrée du centre commercial, parking B...",
        paymentMethod: "Mode de paiement",
        paymentSlip: "Justificatif de paiement",
        attachPaymentSlip: "Touchez pour joindre une capture du paiement",
        payNow: "Envoyer la commande",
        checkout: "Commander sur WhatsApp",

        orderPlaced: "Commande envoyée !",
        orderPlacedSuccess: "Commande envoyée avec succès !",
        redirectingToPayment: "Redirection vers le paiement...",
        redirectingToPaypal: "Redirection vers PayPal...",
        openingWhatsapp: "Ouverture de WhatsApp...",
        geoNotSupported: "La géolocalisation n'est pas prise en charge par votre navigateur",
        geoFailed: "Impossible d'obtenir votre position",

        orderLabel: "Commande",
        poweredBy: "Propulsé par",

        newOrder: "NOUVELLE COMMANDE",
        customerDetails: "Coordonnées du client",
        orderItems: "Articles commandés",
        paymentLabel: "Paiement",
        notesLabel: "Notes",
        paymentSlipLabel: "Justificatif",
        trackLabel: "Suivi",

        fulfillmentDelivery: "Livraison",
        fulfillmentPickup: "Retrait",
        fulfillmentDinein: "Sur place",
        fulfillmentPost: "Envoi par courrier",
    },
    ar: {
        searchPlaceholder: "ابحث في القائمة...",
        all: "الكل",
        addToOrder: "أضف للطلب",
        viewCart: "عرض الطلب",
        viewCartBtn: "عرض السلة",
        outOfStock: "نفذت الكمية",
        items: "عناصر",
        openNow: "مفتوح الآن",
        closed: "مغلق",

        emptyCart: "سلة المشتريات فارغة",
        checkoutTitle: "إتمام الطلب",
        digital: "رقمي",
        subtotal: "المجموع الفرعي",
        delivery: "التوصيل",
        discount: "خصم",
        total: "المجموع",
        promoCode: "كود الخصم",
        apply: "تطبيق",
        name: "الاسم",
        phone: "رقم الواتساب",
        email: "البريد الإلكتروني",
        address: "عنوان التوصيل",
        pinCode: "رابط الموقع (اختياري)",
        notes: "ملاحظات",
        notesPlaceholder: "مثال: بدون بصل، صلصة إضافية، الرجاء قرع الجرس...",
        addressPlaceholder: "الشارع، المدينة، المبنى...",
        fullNamePlaceholder: "الاسم الكامل",
        phonePlaceholder: "+1234567890",
        emailPlaceholder: "you@example.com",
        locationHelpPlaceholder: "مثال: مدخل المول، موقف السيارات B...",
        paymentMethod: "طريقة الدفع",
        paymentSlip: "إيصال الدفع",
        attachPaymentSlip: "اضغط لإرفاق صورة الدفع",
        payNow: "إرسال الطلب",
        checkout: "اطلب عبر واتساب",

        orderPlaced: "تم إرسال الطلب!",
        orderPlacedSuccess: "تم إرسال الطلب بنجاح!",
        redirectingToPayment: "جاري التحويل إلى الدفع...",
        redirectingToPaypal: "جاري التحويل إلى PayPal...",
        openingWhatsapp: "جاري فتح واتساب...",
        geoNotSupported: "متصفحك لا يدعم تحديد الموقع",
        geoFailed: "تعذر الحصول على موقعك",

        orderLabel: "طلب",
        poweredBy: "مدعوم بواسطة",

        newOrder: "طلب جديد",
        customerDetails: "بيانات العميل",
        orderItems: "عناصر الطلب",
        paymentLabel: "الدفع",
        notesLabel: "ملاحظات",
        paymentSlipLabel: "إيصال الدفع",
        trackLabel: "تتبع",

        fulfillmentDelivery: "توصيل",
        fulfillmentPickup: "استلام من المحل",
        fulfillmentDinein: "تناول في المحل",
        fulfillmentPost: "شحن بالبريد",
    },
    pt: {
        searchPlaceholder: "Buscar no cardápio...",
        all: "Todos",
        addToOrder: "Adicionar",
        viewCart: "Ver Pedido",
        viewCartBtn: "Ver Carrinho",
        outOfStock: "Esgotado",
        items: "itens",
        openNow: "Aberto",
        closed: "Fechado",

        emptyCart: "Seu carrinho está vazio",
        checkoutTitle: "Finalizar Pedido",
        digital: "Digital",
        subtotal: "Subtotal",
        delivery: "Entrega",
        discount: "Desconto",
        total: "Total",
        promoCode: "Código Promocional",
        apply: "Aplicar",
        name: "Nome",
        phone: "Número do WhatsApp",
        email: "E-mail",
        address: "Endereço de Entrega",
        pinCode: "Link do Maps (Opcional)",
        notes: "Observações",
        notesPlaceholder: "ex. Sem cebola, molho extra, tocar a campainha...",
        addressPlaceholder: "Rua, Cidade, Edifício...",
        fullNamePlaceholder: "Nome completo",
        phonePlaceholder: "+5511999999999",
        emailPlaceholder: "voce@exemplo.com",
        locationHelpPlaceholder: "ex. Entrada do shopping, estacionamento B...",
        paymentMethod: "Forma de pagamento",
        paymentSlip: "Comprovante de pagamento",
        attachPaymentSlip: "Toque para anexar o comprovante",
        payNow: "Enviar Pedido",
        checkout: "Pedir pelo WhatsApp",

        orderPlaced: "Pedido enviado!",
        orderPlacedSuccess: "Pedido enviado com sucesso!",
        redirectingToPayment: "Redirecionando para pagamento...",
        redirectingToPaypal: "Redirecionando para PayPal...",
        openingWhatsapp: "Abrindo WhatsApp...",
        geoNotSupported: "Seu navegador não suporta geolocalização",
        geoFailed: "Não foi possível obter sua localização",

        orderLabel: "Pedido",
        poweredBy: "Desenvolvido por",

        newOrder: "NOVO PEDIDO",
        customerDetails: "Dados do Cliente",
        orderItems: "Itens do Pedido",
        paymentLabel: "Pagamento",
        notesLabel: "Observações",
        paymentSlipLabel: "Comprovante",
        trackLabel: "Acompanhar",

        fulfillmentDelivery: "Entrega",
        fulfillmentPickup: "Retirada",
        fulfillmentDinein: "Comer no local",
        fulfillmentPost: "Envio pelos Correios",
    },
    id: {
        searchPlaceholder: "Cari menu...",
        all: "Semua",
        addToOrder: "Tambahkan",
        viewCart: "Lihat Pesanan",
        viewCartBtn: "Lihat Keranjang",
        outOfStock: "Habis",
        items: "item",
        openNow: "Buka",
        closed: "Tutup",

        emptyCart: "Keranjang Anda kosong",
        checkoutTitle: "Pembayaran",
        digital: "Digital",
        subtotal: "Subtotal",
        delivery: "Pengiriman",
        discount: "Diskon",
        total: "Total",
        promoCode: "Kode Promo",
        apply: "Terapkan",
        name: "Nama",
        phone: "Nomor WhatsApp",
        email: "Email",
        address: "Alamat Pengiriman",
        pinCode: "Link Maps (Opsional)",
        notes: "Catatan",
        notesPlaceholder: "mis. Tanpa bawang, saus tambahan, bunyikan bel...",
        addressPlaceholder: "Jalan, Kota, Gedung...",
        fullNamePlaceholder: "Nama lengkap",
        phonePlaceholder: "+628123456789",
        emailPlaceholder: "anda@contoh.com",
        locationHelpPlaceholder: "mis. Pintu masuk mall, parkir B...",
        paymentMethod: "Metode pembayaran",
        paymentSlip: "Bukti Pembayaran",
        attachPaymentSlip: "Ketuk untuk lampirkan bukti pembayaran",
        payNow: "Kirim Pesanan",
        checkout: "Pesan via WhatsApp",

        orderPlaced: "Pesanan terkirim!",
        orderPlacedSuccess: "Pesanan berhasil dikirim!",
        redirectingToPayment: "Mengalihkan ke pembayaran...",
        redirectingToPaypal: "Mengalihkan ke PayPal...",
        openingWhatsapp: "Membuka WhatsApp...",
        geoNotSupported: "Browser Anda tidak mendukung geolokasi",
        geoFailed: "Tidak dapat mengambil lokasi Anda",

        orderLabel: "Pesanan",
        poweredBy: "Dibuat oleh",

        newOrder: "PESANAN BARU",
        customerDetails: "Data Pelanggan",
        orderItems: "Item Pesanan",
        paymentLabel: "Pembayaran",
        notesLabel: "Catatan",
        paymentSlipLabel: "Bukti Pembayaran",
        trackLabel: "Lacak",

        fulfillmentDelivery: "Pengiriman",
        fulfillmentPickup: "Ambil sendiri",
        fulfillmentDinein: "Makan di tempat",
        fulfillmentPost: "Pengiriman via Pos",
    },
};

export type Dictionary = typeof dictionaries.en;

export const getDictionary = (locale: Locale): Dictionary => dictionaries[locale] || dictionaries.en;

/**
 * Auto-detect the best locale from browser language.
 * Maps browser lang codes to our supported locales.
 */
export function detectLocale(): Locale {
    if (typeof navigator === 'undefined') return 'en';

    const browserLang = (navigator.language || '').toLowerCase();

    if (browserLang.startsWith('ar')) return 'ar';
    if (browserLang.startsWith('pt')) return 'pt';
    if (browserLang.startsWith('id') || browserLang.startsWith('ms')) return 'id'; // Malay close to Indonesian
    if (browserLang.startsWith('es')) return 'es';
    if (browserLang.startsWith('fr')) return 'fr';

    return 'en';
}
